server:
  port: 8081

spring:
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka 서버 주소.
management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청 추적
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans

endpoints:
  web:
    exposure:
      include: '*'

  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
